/**
 * Sample subscription data for testing and demonstration
 * Based on real-world subscription services
 */

import { Subscription } from '@/types/subscription';

export const sampleSubscriptions: Subscription[] = [
  {
    id: '1',
    name: 'Netflix',
    plan: 'Premium',
    logo: 'https://www.google.com/s2/favicons?domain=netflix.com&sz=64',
    logo_url: 'https://www.google.com/s2/favicons?domain=netflix.com&sz=64',
    fallback_icon: '🎬',
    cost: 15.99,
    currency: 'USD',
    billing_cycle: 'Monthly',
    category: 'Streaming Service',
    description: 'Unlimited movies and TV shows',
    url: 'https://netflix.com',
    status: 'active',
    account_email: 'user@example.com',
    renewal_date: new Date('2024-02-15'),
    start_date: new Date('2023-01-15'),
    tags: ['entertainment', 'streaming'],
    usage_importance: 'high',
    usage_frequency: 'daily',
    alternative_services: ['Disney+', 'Hulu', 'Amazon Prime'],
    last_used: new Date('2024-01-20'),
    auto_renew: true
  },
  {
    id: '2',
    name: 'ChatGPT Plus',
    plan: 'Pro',
    logo: 'https://www.google.com/s2/favicons?domain=chat.openai.com&sz=64',
    logo_url: 'https://www.google.com/s2/favicons?domain=chat.openai.com&sz=64',
    fallback_icon: '🤖',
    cost: 20.00,
    currency: 'USD',
    billing_cycle: 'Monthly',
    category: 'AI Tools',
    description: 'Advanced AI assistant with GPT-4 access',
    url: 'https://chat.openai.com',
    status: 'active',
    account_email: 'user@example.com',
    renewal_date: new Date('2024-02-10'),
    start_date: new Date('2023-06-10'),
    tags: ['ai', 'productivity', 'writing'],
    usage_importance: 'high',
    usage_frequency: 'daily',
    alternative_services: ['Claude Pro', 'Perplexity Pro', 'Gemini Advanced'],
    last_used: new Date('2024-01-21'),
    auto_renew: true
  },
  {
    id: '3',
    name: 'Spotify',
    plan: 'Premium',
    logo: 'https://www.google.com/s2/favicons?domain=spotify.com&sz=64',
    logo_url: 'https://www.google.com/s2/favicons?domain=spotify.com&sz=64',
    fallback_icon: '🎵',
    cost: 9.99,
    currency: 'USD',
    billing_cycle: 'Monthly',
    category: 'Entertainment',
    description: 'Music streaming service',
    url: 'https://spotify.com',
    status: 'active',
    account_email: 'user@example.com',
    renewal_date: new Date('2024-02-05'),
    start_date: new Date('2022-03-05'),
    tags: ['music', 'entertainment'],
    usage_importance: 'medium',
    usage_frequency: 'daily',
    alternative_services: ['Apple Music', 'YouTube Music', 'Amazon Music'],
    last_used: new Date('2024-01-21'),
    auto_renew: true
  },
  {
    id: '4',
    name: 'Adobe Creative Cloud',
    plan: 'All Apps',
    logo: 'https://www.google.com/s2/favicons?domain=adobe.com&sz=64',
    logo_url: 'https://www.google.com/s2/favicons?domain=adobe.com&sz=64',
    fallback_icon: '🎨',
    cost: 52.99,
    currency: 'USD',
    billing_cycle: 'Monthly',
    category: 'Design Tools',
    description: 'Complete creative suite',
    url: 'https://adobe.com',
    status: 'active',
    account_email: 'user@example.com',
    renewal_date: new Date('2024-02-20'),
    start_date: new Date('2023-08-20'),
    tags: ['design', 'creative', 'professional'],
    usage_importance: 'high',
    usage_frequency: 'weekly',
    alternative_services: ['Figma', 'Canva Pro', 'Sketch'],
    last_used: new Date('2024-01-18'),
    auto_renew: true
  },
  {
    id: '5',
    name: 'GitHub Copilot',
    plan: 'Individual',
    logo: 'https://www.google.com/s2/favicons?domain=github.com&sz=64',
    logo_url: 'https://www.google.com/s2/favicons?domain=github.com&sz=64',
    fallback_icon: '🤖',
    cost: 10.00,
    currency: 'USD',
    billing_cycle: 'Monthly',
    category: 'Development Tools',
    description: 'AI-powered code completion',
    url: 'https://github.com/features/copilot',
    status: 'active',
    account_email: 'user@example.com',
    renewal_date: new Date('2024-02-12'),
    start_date: new Date('2023-09-12'),
    tags: ['ai', 'development', 'coding'],
    usage_importance: 'high',
    usage_frequency: 'daily',
    alternative_services: ['Tabnine', 'CodeWhisperer', 'Cursor'],
    last_used: new Date('2024-01-21'),
    auto_renew: true
  },
  {
    id: '6',
    name: 'Notion',
    plan: 'Pro',
    logo: 'https://www.google.com/s2/favicons?domain=notion.so&sz=64',
    logo_url: 'https://www.google.com/s2/favicons?domain=notion.so&sz=64',
    fallback_icon: '📝',
    cost: 8.00,
    currency: 'USD',
    billing_cycle: 'Monthly',
    category: 'Productivity',
    description: 'All-in-one workspace',
    url: 'https://notion.so',
    status: 'active',
    account_email: 'user@example.com',
    renewal_date: new Date('2024-02-08'),
    start_date: new Date('2023-04-08'),
    tags: ['productivity', 'notes', 'organization'],
    usage_importance: 'medium',
    usage_frequency: 'daily',
    alternative_services: ['Obsidian', 'Roam Research', 'Logseq'],
    last_used: new Date('2024-01-20'),
    auto_renew: true
  },
  {
    id: '7',
    name: 'Figma',
    plan: 'Professional',
    logo: 'https://www.google.com/s2/favicons?domain=figma.com&sz=64',
    logo_url: 'https://www.google.com/s2/favicons?domain=figma.com&sz=64',
    fallback_icon: '🎨',
    cost: 12.00,
    currency: 'USD',
    billing_cycle: 'Monthly',
    category: 'Design Tools',
    description: 'Collaborative design platform',
    url: 'https://figma.com',
    status: 'paused',
    account_email: 'user@example.com',
    renewal_date: new Date('2024-02-25'),
    start_date: new Date('2023-07-25'),
    tags: ['design', 'collaboration', 'ui'],
    usage_importance: 'medium',
    usage_frequency: 'weekly',
    alternative_services: ['Adobe XD', 'Sketch', 'Framer'],
    last_used: new Date('2024-01-10'),
    auto_renew: false
  },
  {
    id: '8',
    name: 'Midjourney',
    plan: 'Standard',
    logo: 'https://www.google.com/s2/favicons?domain=midjourney.com&sz=64',
    logo_url: 'https://www.google.com/s2/favicons?domain=midjourney.com&sz=64',
    fallback_icon: '🎨',
    cost: 30.00,
    currency: 'USD',
    billing_cycle: 'Monthly',
    category: 'AI Tools',
    description: 'AI image generation',
    url: 'https://midjourney.com',
    status: 'active',
    account_email: 'user@example.com',
    renewal_date: new Date('2024-02-18'),
    start_date: new Date('2023-11-18'),
    tags: ['ai', 'image', 'generation'],
    usage_importance: 'medium',
    usage_frequency: 'weekly',
    alternative_services: ['DALL-E', 'Stable Diffusion', 'Firefly'],
    last_used: new Date('2024-01-19'),
    auto_renew: true
  },
  {
    id: '9',
    name: 'Dropbox',
    plan: 'Plus',
    logo: 'https://www.google.com/s2/favicons?domain=dropbox.com&sz=64',
    logo_url: 'https://www.google.com/s2/favicons?domain=dropbox.com&sz=64',
    fallback_icon: '📁',
    cost: 9.99,
    currency: 'USD',
    billing_cycle: 'Monthly',
    category: 'Cloud Provider',
    description: 'Cloud storage and file sharing',
    url: 'https://dropbox.com',
    status: 'active',
    account_email: 'user@example.com',
    renewal_date: new Date('2024-02-14'),
    start_date: new Date('2022-12-14'),
    tags: ['storage', 'cloud', 'sync'],
    usage_importance: 'low',
    usage_frequency: 'monthly',
    alternative_services: ['Google Drive', 'OneDrive', 'iCloud'],
    last_used: new Date('2024-01-15'),
    auto_renew: true
  },
  {
    id: '10',
    name: 'Grammarly',
    plan: 'Premium',
    logo: 'https://www.google.com/s2/favicons?domain=grammarly.com&sz=64',
    logo_url: 'https://www.google.com/s2/favicons?domain=grammarly.com&sz=64',
    fallback_icon: '✍️',
    cost: 12.00,
    currency: 'USD',
    billing_cycle: 'Monthly',
    category: 'Productivity',
    description: 'AI-powered writing assistant',
    url: 'https://grammarly.com',
    status: 'canceled',
    account_email: 'user@example.com',
    renewal_date: new Date('2024-01-30'),
    start_date: new Date('2023-01-30'),
    tags: ['writing', 'grammar', 'ai'],
    usage_importance: 'low',
    usage_frequency: 'rarely',
    alternative_services: ['ProWritingAid', 'LanguageTool', 'Hemingway'],
    last_used: new Date('2024-01-05'),
    auto_renew: false
  }
];

/**
 * Initialize sample data in localStorage if no data exists
 */
export function initializeSampleData(): void {
  if (typeof window === 'undefined') return;
  
  const existing = localStorage.getItem('subscription-manager-subscriptions');
  if (!existing || JSON.parse(existing).length === 0) {
    localStorage.setItem('subscription-manager-subscriptions', JSON.stringify(sampleSubscriptions));
  }
}
