-- ============================================================================
-- INSERT SUBSCRIPTION DATA FROM toolsSubscription6.json
-- ============================================================================
-- Generated on: 2025-10-07 20:37:47
-- ============================================================================

BEGIN;

-- ============================================================================
-- INSERT MAIN SUBSCRIPTION DATA
-- ============================================================================

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('1', 'ChatGPT', 'AI Tools', 'Chat', 'Advanced AI assistant with GPT-4 access, faster responses, and priority access during peak hours.', 'https://chat.openai.com', 'https://icons.duckduckgo.com/ip3/chat.openai.com.ico', 'plus', 20.0, 'USD', 'monthly', 'active', 'Essential for work projects and research. Great for coding assistance.', '2025-01-05T00:00:00.000Z', '2024-07-05T00:00:00.000Z', '🤖', 'daily', 'high', 'secret-key-example', false, true, 1, 'user@example.com', false, true, false, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('2', 'Claude', 'AI Tools', 'Chat', 'AI assistant by Anthropic with advanced reasoning capabilities and safety features.', 'https://claude.ai', 'https://icons.duckduckgo.com/ip3/claude.ai.ico', 'pro', 20.0, 'USD', 'monthly', 'active', 'Great for complex reasoning and analysis tasks.', '2025-02-01T00:00:00.000Z', '2024-08-01T00:00:00.000Z', '🧠', 'daily', 'high', 'claude-secret-key', false, true, 7, 'user@example.com', false, true, false, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('3', 'Gemini', 'AI Tools', 'Chat', 'Google''s advanced AI model with multimodal capabilities and integration with Google services.', 'https://gemini.google.com', 'https://icons.duckduckgo.com/ip3/gemini.google.com.ico', 'advanced', 20.0, 'USD', 'monthly', 'active', 'Excellent for multimodal tasks and Google workspace integration.', '2025-01-15T00:00:00.000Z', '2024-07-15T00:00:00.000Z', '💎', 'weekly', 'medium', '', false, true, 2, 'user@example.com', false, true, false, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('4', 'deepseek', 'AI Tools', 'Chat', 'Advanced AI model with strong coding and reasoning capabilities.', 'https://deepseek.com', 'https://icons.duckduckgo.com/ip3/deepseek.com.ico', 'pro', 15.0, 'USD', 'monthly', 'active', 'Great for coding tasks and technical analysis.', NULL, NULL, '🔍', 'weekly', 'medium', '', false, true, 3, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('5', 'Meta AI', 'AI Tools', 'Chat', 'Meta''s AI assistant with integration across Meta''s platforms.', 'https://ai.meta.com', 'https://icons.duckduckgo.com/ip3/ai.meta.com.ico', 'free', 0.0, 'USD', 'monthly', 'active', 'Free AI assistant integrated with Meta platforms.', NULL, NULL, '🔵', 'rarely', 'low', '', false, true, 46, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('6', 'Grok', 'AI Tools', 'Chat', 'X''s AI assistant with real-time information and unique personality.', 'https://grok.x.ai', 'https://icons.duckduckgo.com/ip3/grok.x.ai.ico', 'premium', 16.0, 'USD', 'monthly', 'active', 'AI with real-time web access and personality.', NULL, NULL, '🚀', 'weekly', 'medium', '', false, true, 4, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('7', 'Poe', 'AI Tools', 'Chat', 'Platform for accessing multiple AI models in one interface.', 'https://poe.com', 'https://icons.duckduckgo.com/ip3/poe.com.ico', 'premium', 19.99, 'USD', 'monthly', 'active', 'Access to multiple AI models through one platform.', NULL, NULL, '💬', 'weekly', 'medium', '', false, true, 37, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('8', 'Monica', 'AI Tools', 'Chat', 'AI assistant with browser extension and productivity features.', 'https://monica.im', 'https://icons.duckduckgo.com/ip3/monica.im.ico', 'pro', 9.99, 'USD', 'monthly', 'active', 'Browser-based AI assistant for productivity.', NULL, NULL, '💬', 'weekly', 'medium', '', false, true, 49, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('9', 'Kimi', 'AI Tools', 'Chat', 'AI assistant with long context understanding capabilities.', 'https://kimi.ai', 'https://icons.duckduckgo.com/ip3/kimi.ai.ico', 'plus', 12.99, 'USD', 'monthly', 'active', 'AI with excellent long context processing.', NULL, NULL, '🤖', 'monthly', 'medium', '', true, true, 17, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('10', 'Qwen3', 'AI Tools', 'Chat', 'Advanced AI model with multilingual capabilities.', 'https://qwen.ai', 'https://icons.duckduckgo.com/ip3/qwen.ai.ico', 'pro', 14.99, 'USD', 'monthly', 'active', 'Multilingual AI with strong performance across languages.', NULL, NULL, '🔷', 'monthly', 'low', '', true, true, 20, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('11', 'Doubao', 'AI Tools', 'Chat', 'ByteDance''s AI assistant with strong Chinese language support.', 'https://doubao.com', 'https://icons.duckduckgo.com/ip3/doubao.com.ico', 'premium', 11.99, 'USD', 'monthly', 'paused', 'AI with excellent Chinese language capabilities.', NULL, NULL, '🎯', 'rarely', 'low', '', true, true, 12, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('12', 'perplexity', 'AI Tools', 'Search', 'AI-powered search engine with real-time information and citations.', 'https://perplexity.ai', 'https://icons.duckduckgo.com/ip3/perplexity.ai.ico', 'pro', 20.0, 'USD', 'monthly', 'active', 'Excellent for research with real-time web search and citations.', '2025-01-12T00:00:00.000Z', '2024-07-12T00:00:00.000Z', '🔮', 'daily', 'high', 'pplx-secret', false, true, 6, 'user@example.com', false, true, false, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('13', 'Google Labs', 'AI Tools', 'Research', 'Google''s experimental AI features and search enhancements.', 'https://labs.google.com', 'https://icons.duckduckgo.com/ip3/labs.google.com.ico', 'free', 0.0, 'USD', 'monthly', 'active', 'Access to experimental Google AI features.', '2025-12-31T00:00:00.000Z', '2024-01-01T00:00:00.000Z', '🧪', 'weekly', 'medium', '', false, true, 39, 'user@example.com', false, true, false, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('14', 'character.ai', 'AI Tools', 'Roleplay', 'Platform for creating and chatting with AI characters.', 'https://character.ai', 'https://icons.duckduckgo.com/ip3/character.ai.ico', 'plus', 9.99, 'USD', 'monthly', 'active', 'Fun platform for creative roleplay with AI characters.', NULL, NULL, '🎭', 'weekly', 'low', '', false, false, 5, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('15', 'JanitorAI', 'AI Tools', 'Roleplay', 'AI roleplay platform with various character types and scenarios.', 'https://janitorai.com', 'https://icons.duckduckgo.com/ip3/janitorai.com.ico', 'premium', 15.0, 'USD', 'monthly', 'active', 'Roleplay AI with diverse character options.', NULL, NULL, '🧹', 'monthly', 'low', '', false, false, 8, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('16', 'Crushon AI', 'AI Tools', 'Roleplay', 'AI companion platform for roleplay and conversation.', 'https://crushon.ai', 'https://icons.duckduckgo.com/ip3/crushon.ai.ico', 'premium', 12.99, 'USD', 'monthly', 'canceled', 'AI companion roleplay platform.', NULL, NULL, '💕', 'rarely', 'low', '', false, false, 24, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('17', 'candy.ai', 'AI Tools', 'Roleplay', 'AI companion and virtual girlfriend platform.', 'https://candy.ai', 'https://icons.duckduckgo.com/ip3/candy.ai.ico', 'premium', 13.99, 'USD', 'monthly', 'paused', 'Virtual companion AI platform.', NULL, NULL, '🍭', 'rarely', 'low', '', false, false, 42, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('18', 'JuicyChat', 'AI Tools', 'Roleplay', 'AI chat platform with various roleplay scenarios.', 'https://juicychat.ai', 'https://icons.duckduckgo.com/ip3/juicychat.ai.ico', 'premium', 11.99, 'USD', 'monthly', 'canceled', 'Roleplay chat AI platform.', NULL, NULL, '💬', 'rarely', 'low', '', false, false, 43, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('19', 'Joi', 'AI Tools', 'Roleplay', 'AI companion platform for personalized conversations.', 'https://joi.ai', 'https://icons.duckduckgo.com/ip3/joi.ai.ico', 'premium', 14.99, 'USD', 'monthly', 'paused', 'Personalized AI companion platform.', NULL, NULL, '⚫', 'rarely', 'low', '', false, false, 48, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('20', 'SPICYCHAT.AI', 'AI Tools', 'Roleplay', 'AI chat platform with spicy roleplay scenarios.', 'https://spicychat.ai', 'https://icons.duckduckgo.com/ip3/spicychat.ai.ico', 'premium', 10.99, 'USD', 'monthly', 'canceled', 'Adult-oriented roleplay AI chat platform.', NULL, NULL, '🌶️', 'rarely', 'low', '', false, false, 14, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('21', 'Midjourney', 'AI Tools', 'Image', 'AI image generation platform with artistic and creative capabilities.', 'https://midjourney.com', 'https://icons.duckduckgo.com/ip3/midjourney.com.ico', 'pro', 30.0, 'USD', 'monthly', 'active', 'Best-in-class AI image generation for creative projects.', NULL, NULL, '🎨', 'daily', 'high', '', false, true, 28, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('22', 'Leonardo.Ai', 'AI Tools', 'Image', 'AI image generation platform with focus on games and creative content.', 'https://leonardo.ai', 'https://icons.duckduckgo.com/ip3/leonardo.ai.ico', 'premium', 24.0, 'USD', 'monthly', 'active', 'Great for game assets and creative image generation.', NULL, NULL, '🎨', 'weekly', 'medium', 'leonardo-secret', false, true, 40, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('23', 'CIVITAI', 'AI Tools', 'Image', 'Community platform for AI art models and generated images.', 'https://civitai.com', 'https://icons.duckduckgo.com/ip3/civitai.com.ico', 'pro', 15.0, 'USD', 'monthly', 'active', 'Community for AI art models and resources.', NULL, NULL, '🎭', 'weekly', 'medium', '', false, true, 32, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('24', 'SEARRT.AI', 'AI Tools', 'Image', 'AI art generation platform with various artistic styles.', 'https://seaart.ai', 'https://icons.duckduckgo.com/ip3/seaart.ai.ico', 'pro', 18.0, 'USD', 'monthly', 'active', 'AI art platform with diverse artistic styles.', NULL, NULL, '🎨', 'monthly', 'medium', '', true, true, 19, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('25', 'Photoroom', 'AI Tools', 'Image', 'AI-powered photo editing with background removal and enhancement features.', 'https://photoroom.com', 'https://icons.duckduckgo.com/ip3/photoroom.com.ico', 'pro', 9.99, 'USD', 'monthly', 'active', 'Excellent for product photos and background removal.', NULL, NULL, '📷', 'weekly', 'medium', '', false, true, 30, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('26', 'Pixelcut', 'AI Tools', 'Image', 'AI-powered image editing and design platform.', 'https://pixelcut.ai', 'https://icons.duckduckgo.com/ip3/pixelcut.ai.ico', 'pro', 7.99, 'USD', 'monthly', 'active', 'Quick and easy AI-powered image editing.', NULL, NULL, '✂️', 'monthly', 'medium', '', false, true, 27, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('27', 'remove.bg', 'AI Tools', 'Image', 'AI-powered automatic background removal tool.', 'https://remove.bg', 'https://icons.duckduckgo.com/ip3/remove.bg.ico', 'pro', 9.0, 'USD', 'monthly', 'active', 'Best tool for automatic background removal.', NULL, NULL, '🖼️', 'weekly', 'medium', 'removebg-secret', false, true, 11, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('28', 'cutout.pro', 'AI Tools', 'Image', 'AI-powered image editing with background removal and enhancement.', 'https://cutout.pro', 'https://icons.duckduckgo.com/ip3/cutout.pro.ico', 'pro', 8.99, 'USD', 'monthly', 'active', 'Comprehensive AI image editing suite.', NULL, NULL, '✂️', 'monthly', 'medium', '', false, true, 34, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('29', 'ourdream.ai', 'AI Tools', 'Image', 'AI image generation platform focused on creative and artistic content.', 'https://ourdream.ai', 'https://icons.duckduckgo.com/ip3/ourdream.ai.ico', 'pro', 12.99, 'USD', 'monthly', 'paused', 'Creative AI image generation platform.', NULL, NULL, '💭', 'rarely', 'low', '', false, true, 50, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('30', 'Unsplash', 'Tools', 'Image', 'High-quality stock photography platform with some AI features.', 'https://unsplash.com', 'https://icons.duckduckgo.com/ip3/unsplash.com.ico', 'premium', 10.0, 'USD', 'monthly', 'active', 'Premium stock photos with AI search capabilities.', '2025-02-28T00:00:00.000Z', '2024-08-28T00:00:00.000Z', '📸', 'weekly', 'medium', '', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('31', 'VEED', 'AI Tools', 'Video', 'AI-powered video editing platform with automated features.', 'https://veed.io', 'https://icons.duckduckgo.com/ip3/veed.io.ico', 'pro', 24.0, 'USD', 'monthly', 'active', 'Great for quick video editing with AI features.', NULL, NULL, '🎬', 'weekly', 'high', '', false, true, 44, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('32', 'KlingAI', 'AI Tools', 'Video', 'AI video generation platform with text-to-video capabilities.', 'https://kling.ai', 'https://icons.duckduckgo.com/ip3/kling.ai.ico', 'pro', 30.0, 'USD', 'monthly', 'active', 'Advanced AI video generation from text prompts.', NULL, NULL, '🎬', 'weekly', 'high', '', true, true, 33, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('33', 'Remaker', 'AI Tools', 'Video', 'AI-powered video editing and face swap platform.', 'https://remaker.ai', 'https://icons.duckduckgo.com/ip3/remaker.ai.ico', 'pro', 15.99, 'USD', 'monthly', 'active', 'AI video editing with face swap capabilities.', NULL, NULL, '🔄', 'monthly', 'medium', '', false, true, 47, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('34', 'Descript', 'AI Tools', 'Video', 'AI-powered video and audio editing with text-based editing.', 'https://descript.com', 'https://icons.duckduckgo.com/ip3/descript.com.ico', 'premium', 24.0, 'USD', 'monthly', 'active', 'Revolutionary text-based video editing platform.', '2025-01-20T00:00:00.000Z', '2024-07-20T00:00:00.000Z', '🎞️', 'weekly', 'high', '', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('35', 'ElevenLabs', 'AI Tools', 'Audio', 'AI voice generation and cloning platform with realistic speech synthesis.', 'https://elevenlabs.io', 'https://icons.duckduckgo.com/ip3/elevenlabs.io.ico', 'premium', 22.0, 'USD', 'monthly', 'active', 'Best-in-class AI voice synthesis and cloning.', NULL, NULL, '🔊', 'daily', 'high', 'eleven-secret', false, true, 21, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('36', 'SUNO', 'AI Tools', 'Audio', 'AI music generation platform that creates songs from text prompts.', 'https://suno.ai', 'https://icons.duckduckgo.com/ip3/suno.ai.ico', 'pro', 20.0, 'USD', 'monthly', 'active', 'Amazing AI music generation from text descriptions.', NULL, NULL, '🎵', 'weekly', 'medium', '', false, true, 15, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('37', 'TurboScribe', 'AI Tools', 'Transcribe', 'AI-powered transcription service with high accuracy and speed.', 'https://turboscribe.ai', 'https://icons.duckduckgo.com/ip3/turboscribe.ai.ico', 'pro', 15.0, 'USD', 'monthly', 'active', 'Fast and accurate AI transcription service.', NULL, NULL, '📝', 'weekly', 'medium', '', false, true, 29, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('38', 'CURSOR', 'AI Tools', 'Build', 'AI-powered code editor with intelligent autocompletion and generation.', 'https://cursor.sh', 'https://icons.duckduckgo.com/ip3/cursor.sh.ico', 'pro', 20.0, 'USD', 'monthly', 'active', 'Revolutionary AI-powered code editor for developers.', '2025-01-05T00:00:00.000Z', '2024-07-05T00:00:00.000Z', '📝', 'daily', 'high', '', false, true, 26, 'user@example.com', false, true, false, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('39', 'replit', 'AI Tools', 'Build', 'Online IDE with AI coding assistance and collaborative features.', 'https://replit.com', 'https://icons.duckduckgo.com/ip3/replit.com.ico', 'pro', 7.0, 'USD', 'monthly', 'active', 'Great online IDE with AI coding assistance.', '2025-01-12T00:00:00.000Z', '2024-07-12T00:00:00.000Z', '💻', 'weekly', 'medium', '', false, true, 41, 'user@example.com', false, true, false, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('40', 'Lovable', 'AI Tools', 'Build', 'AI-powered app building platform with visual development.', 'https://lovable.dev', 'https://icons.duckduckgo.com/ip3/lovable.dev.ico', 'pro', 25.0, 'USD', 'monthly', 'active', 'Visual AI app development platform.', '2025-02-15T00:00:00.000Z', '2024-08-15T00:00:00.000Z', '💚', 'monthly', 'medium', '', false, true, 23, 'user@example.com', false, true, false, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('41', 'Bolt.new', 'AI Tools', 'Build', 'AI-powered web development platform for rapid prototyping.', 'https://bolt.new', 'https://icons.duckduckgo.com/ip3/bolt.new.ico', 'pro', 20.0, 'USD', 'monthly', 'active', 'Rapid web development with AI assistance.', '2025-01-30T00:00:00.000Z', '2024-07-30T00:00:00.000Z', '⚡', 'weekly', 'medium', '', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('42', 'v0', 'AI Tools', 'Build', 'Vercel''s AI-powered UI generation tool for React components.', 'https://v0.dev', 'https://icons.duckduckgo.com/ip3/v0.dev.ico', 'pro', 20.0, 'USD', 'monthly', 'active', 'AI-generated React components from text descriptions.', NULL, NULL, '🎨', 'weekly', 'medium', '', false, true, NULL, 'user@example.com', false, false, true, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('43', 'ChatPRD', 'AI Tools', 'Build', 'AI-powered product requirements document generation tool.', 'https://chatprd.ai', 'https://icons.duckduckgo.com/ip3/chatprd.ai.ico', 'pro', 15.0, 'USD', 'monthly', 'active', 'AI tool for generating product requirement documents.', '2025-02-20T00:00:00.000Z', '2024-08-20T00:00:00.000Z', '📋', 'monthly', 'medium', '', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('44', 'NotebookLM', 'AI Tools', 'Research', 'Google''s AI-powered research and writing assistant.', 'https://notebooklm.google.com', 'https://icons.duckduckgo.com/ip3/notebooklm.google.com.ico', 'free', 0.0, 'USD', 'monthly', 'active', 'Excellent AI research assistant from Google.', '2025-12-31T00:00:00.000Z', '2024-01-01T00:00:00.000Z', '📓', 'daily', 'high', '', false, true, 13, 'user@example.com', false, true, false, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('45', 'GAMMA', 'AI Tools', 'Write', 'AI-powered presentation and document creation platform.', 'https://gamma.app', 'https://icons.duckduckgo.com/ip3/gamma.app.ico', 'pro', 15.0, 'USD', 'monthly', 'active', 'Great for creating presentations with AI assistance.', '2025-01-18T00:00:00.000Z', '2024-07-18T00:00:00.000Z', '📊', 'weekly', 'medium', '', false, true, 25, 'user@example.com', false, true, false, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('46', 'QuillBot', 'AI Tools', 'Write', 'AI-powered writing assistant with paraphrasing and grammar checking.', 'https://quillbot.com', 'https://icons.duckduckgo.com/ip3/quillbot.com.ico', 'premium', 8.33, 'USD', 'monthly', 'active', 'Excellent for writing improvement and paraphrasing.', NULL, NULL, '✍️', 'weekly', 'medium', '', false, true, 16, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('47', 'manus', 'AI Tools', 'Write', 'AI-powered writing and editing assistant for content creators.', 'https://manus.app', 'https://icons.duckduckgo.com/ip3/manus.app.ico', 'pro', 12.0, 'USD', 'monthly', 'paused', 'Writing assistant for content creators.', NULL, NULL, '🖐️', 'rarely', 'low', '', false, true, 31, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('48', 'Hugging Face', 'AI Tools', 'Development', 'Platform for machine learning models and AI development tools.', 'https://huggingface.co', 'https://icons.duckduckgo.com/ip3/huggingface.co.ico', 'pro', 9.0, 'USD', 'monthly', 'active', 'Essential platform for ML development and model hosting.', '2025-01-15T00:00:00.000Z', '2024-07-15T00:00:00.000Z', '🤗', 'daily', 'high', 'hf-secret', false, true, 22, 'user@example.com', false, true, false, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('49', 'Google AI Studio', 'AI Tools', 'Development', 'Google''s platform for AI model development and experimentation.', 'https://aistudio.google.com', 'https://icons.duckduckgo.com/ip3/aistudio.google.com.ico', 'free', 0.0, 'USD', 'monthly', 'active', 'Google''s AI development and experimentation platform.', '2025-12-31T00:00:00.000Z', '2024-01-01T00:00:00.000Z', '🎨', 'weekly', 'medium', '', false, true, 10, 'user@example.com', false, true, false, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('50', 'DeepAI', 'AI Tools', 'Development', 'Platform for AI APIs and development tools.', 'https://deepai.org', 'https://icons.duckduckgo.com/ip3/deepai.org.ico', 'pro', 5.0, 'USD', 'monthly', 'active', 'AI APIs for various development use cases.', NULL, NULL, '🧠', 'monthly', 'medium', '', false, true, 36, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('51', 'Claude Code', 'AI Tools', 'Development', 'Anthropic''s AI coding assistant with advanced programming capabilities.', 'https://www.anthropic.com/claude-code', 'https://icons.duckduckgo.com/ip3/anthropic.com.ico', 'pro', 25.0, 'USD', 'monthly', 'active', 'Advanced AI coding assistant from Anthropic.', '2025-02-12T00:00:00.000Z', '2024-08-12T00:00:00.000Z', '💻', 'daily', 'high', 'claude-code-secret', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('52', 'ZeroGPT', 'AI Tools', 'Utils', 'AI detection tool for identifying AI-generated content.', 'https://zerogpt.com', 'https://icons.duckduckgo.com/ip3/zerogpt.com.ico', 'pro', 9.99, 'USD', 'monthly', 'active', 'Tool for detecting AI-generated text content.', NULL, NULL, '🔍', 'weekly', 'medium', '', false, true, 38, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('53', 'Quark', 'AI Tools', 'Platform', 'AI-powered productivity and utility application.', 'https://quark.app', 'https://icons.duckduckgo.com/ip3/quark.app.ico', 'pro', 7.99, 'USD', 'monthly', 'active', 'Productivity app with AI-powered features.', NULL, NULL, '⚛️', 'weekly', 'medium', '', false, true, 9, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('54', 'Warp', 'AI Tools', 'Development', 'AI-powered terminal with intelligent command suggestions.', 'https://warp.dev', 'https://icons.duckduckgo.com/ip3/warp.dev.ico', 'team', 20.0, 'USD', 'monthly', 'active', 'Revolutionary AI-powered terminal for developers.', '2025-01-05T00:00:00.000Z', '2024-07-05T00:00:00.000Z', '🚀', 'daily', 'high', '', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('55', 'Zapier', 'Tools', 'Automation', 'Automation platform with AI-powered workflow creation.', 'https://zapier.com', 'https://icons.duckduckgo.com/ip3/zapier.com.ico', 'pro', 49.0, 'USD', 'monthly', 'active', 'Essential automation platform for workflow integration.', '2025-01-08T00:00:00.000Z', '2024-07-08T00:00:00.000Z', '⚡', 'daily', 'high', 'zapier-secret', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('56', 'n8n', 'Tools', 'Automation', 'Open-source workflow automation platform with AI integrations.', 'https://n8n.io', 'https://icons.duckduckgo.com/ip3/n8n.io.ico', 'pro', 20.0, 'USD', 'monthly', 'active', 'Open-source workflow automation with AI capabilities.', '2025-02-25T00:00:00.000Z', '2024-08-25T00:00:00.000Z', '🔧', 'weekly', 'medium', '', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('57', 'Pinecone', 'AI Tools', 'Vector DB', 'Vector database for AI applications and semantic search.', 'https://pinecone.io', 'https://icons.duckduckgo.com/ip3/pinecone.io.ico', 'free', 70.0, 'USD', 'monthly', 'active', 'Vector database for AI and machine learning applications.', NULL, NULL, '🌲', 'daily', 'high', 'pinecone-secret', false, true, NULL, 'user@example.com', false, false, true, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('58', 'Weaviate', 'AI Tools', 'Vector DB', 'Open-source vector database with AI and ML capabilities.', 'https://weaviate.io', 'https://icons.duckduckgo.com/ip3/weaviate.io.ico', 'free', 25.0, 'USD', 'monthly', 'active', 'Open-source vector database for AI applications.', NULL, NULL, '🕸️', 'weekly', 'medium', '', false, true, NULL, 'user@example.com', false, false, true, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('59', 'Amadeus', 'Tools', 'APIs', 'Travel and airline API platform for booking and travel data.', 'https://developers.amadeus.com', 'https://icons.duckduckgo.com/ip3/developers.amadeus.com.ico', 'free', 0.0, 'USD', 'monthly', 'active', 'Travel and airline data APIs for applications.', '2025-12-31T00:00:00.000Z', '2024-01-01T00:00:00.000Z', '✈️', 'monthly', 'medium', 'amadeus-secret', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('60', 'Linear', 'AI Tools', 'Productivity', 'Modern project management and issue tracking with AI features.', 'https://linear.app', 'https://icons.duckduckgo.com/ip3/linear.app.ico', 'pro', 8.0, 'USD', 'monthly', 'active', 'Excellent project management tool for development teams.', '2025-01-20T00:00:00.000Z', '2024-07-20T00:00:00.000Z', '📊', 'daily', 'high', '', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('61', 'Magic Patterns', 'AI Tools', 'Design/Prototype', 'AI-powered design pattern generator for UI/UX design.', 'https://magicpatterns.com', 'https://icons.duckduckgo.com/ip3/magicpatterns.com.ico', 'pro', 15.0, 'USD', 'monthly', 'active', 'AI-powered design patterns for UI development.', '2025-02-05T00:00:00.000Z', '2024-08-05T00:00:00.000Z', '✨', 'weekly', 'medium', '', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('62', 'Figma', 'AI Tools', 'Design/Prototype', 'Collaborative design platform with AI-powered design features.', 'https://figma.com', 'https://icons.duckduckgo.com/ip3/figma.com.ico', 'pro', 12.0, 'USD', 'monthly', 'active', 'Essential design and prototyping platform.', '2025-01-10T00:00:00.000Z', '2024-07-10T00:00:00.000Z', '🎨', 'daily', 'high', '', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('63', 'Mobbin', 'AI Tools', 'Design/Prototype', 'Mobile and web design inspiration platform with AI categorization.', 'https://mobbin.com', 'https://icons.duckduckgo.com/ip3/mobbin.com.ico', 'pro', 8.0, 'USD', 'monthly', 'active', 'Design inspiration platform for mobile and web.', '2025-02-15T00:00:00.000Z', '2024-08-15T00:00:00.000Z', '📱', 'weekly', 'medium', '', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('64', 'WisprFlow', 'AI Tools', 'Speech-to-text', 'AI-powered speech-to-text transcription service.', 'https://wisprflow.ai', 'https://icons.duckduckgo.com/ip3/wisprflow.ai.ico', 'pro', 12.99, 'USD', 'monthly', 'active', 'Advanced speech-to-text AI transcription.', '2025-02-22T00:00:00.000Z', '2024-08-22T00:00:00.000Z', '🎤', 'weekly', 'medium', '', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('65', 'Raycast', 'AI Tools', 'Productivity', 'Productivity launcher with AI-powered features and extensions.', 'https://raycast.com', 'https://icons.duckduckgo.com/ip3/raycast.com.ico', 'pro', 8.0, 'USD', 'monthly', 'active', 'Productivity launcher with powerful AI extensions.', '2025-01-25T00:00:00.000Z', '2024-07-25T00:00:00.000Z', '🚀', 'daily', 'high', '', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('66', 'Granola', 'AI Tools', 'Productivity', 'AI-powered meeting notes and transcription service.', 'https://granola.ai', 'https://icons.duckduckgo.com/ip3/granola.ai.ico', 'pro', 15.0, 'USD', 'monthly', 'active', 'AI meeting notes and transcription service.', '2025-02-28T00:00:00.000Z', '2024-08-28T00:00:00.000Z', '🥣', 'daily', 'medium', '', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('67', 'Superhuman', 'AI Tools', 'Productivity', 'AI-powered email client with advanced productivity features.', 'https://superhuman.com', 'https://icons.duckduckgo.com/ip3/superhuman.com.ico', 'personal', 30.0, 'USD', 'monthly', 'active', 'Premium AI-powered email client for productivity.', '2025-01-15T00:00:00.000Z', '2024-07-15T00:00:00.000Z', '⚡', 'daily', 'high', '', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('68', 'Notion', 'AI Tools', 'Productivity', 'All-in-one workspace with AI writing and organization features.', 'https://notion.so', 'https://icons.duckduckgo.com/ip3/notion.so.ico', 'plus', 8.0, 'USD', 'monthly', 'active', 'Essential workspace with AI writing capabilities.', '2025-01-05T00:00:00.000Z', '2024-07-05T00:00:00.000Z', '📝', 'daily', 'high', '', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('69', 'Supabase', 'Tools', 'DB', 'Open-source database platform with AI and vector capabilities.', 'https://supabase.com', 'https://icons.duckduckgo.com/ip3/supabase.com.ico', 'pro', 25.0, 'USD', 'monthly', 'active', 'Open-source database with AI and vector support.', '2025-01-18T00:00:00.000Z', '2024-07-18T00:00:00.000Z', '🐘', 'daily', 'high', 'supabase-secret', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('70', 'Vercel', 'Tools', 'Deploy', 'Frontend deployment platform with AI-powered optimization.', 'https://vercel.com', 'https://icons.duckduckgo.com/ip3/vercel.com.ico', 'pro', 20.0, 'USD', 'monthly', 'active', 'Premier platform for frontend deployment and hosting.', '2025-01-08T00:00:00.000Z', '2024-07-08T00:00:00.000Z', '▲', 'daily', 'high', 'vercel-secret', false, true, NULL, 'user@example.com', false, true, false, true);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('71', 'Hailuo AI', 'AI Tools', 'Platform', 'AI platform with various generative capabilities.', 'https://hailuo.ai', 'https://icons.duckduckgo.com/ip3/hailuo.ai.ico', 'pro', 16.99, 'USD', 'monthly', 'paused', 'Multi-purpose AI platform with various capabilities.', NULL, NULL, '🌀', 'rarely', 'low', '', true, true, 45, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('72', 'PolyBuzz', 'AI Tools', 'Platform', 'AI-powered social media and content analysis platform.', 'https://polybuzz.ai', 'https://icons.duckduckgo.com/ip3/polybuzz.ai.ico', 'pro', 14.99, 'USD', 'monthly', 'canceled', 'AI platform for social media content analysis.', NULL, NULL, '🐝', 'rarely', 'low', '', false, true, 18, 'user@example.com', false, false, true, false);

INSERT INTO subscriptions (id, name, category, subcategory, description, url, logo_url, plan, cost, currency, billing_cycle, status, notes, renewal_date, start_date, fallback_icon, usage_frequency, usage_importance, secret_key, china_region_only, safe_for_work, a16z_rank, account_email, auto_renew, iam_using_it, no_subscription, not_in_a16z) VALUES ('73', 'Adot', 'AI Tools', 'Other', 'AI-powered search and discovery platform.', 'https://adot.ai', 'https://icons.duckduckgo.com/ip3/adot.ai.ico', 'premium', 11.99, 'USD', 'monthly', 'active', 'AI-powered search and discovery platform.', NULL, NULL, '🔍', 'monthly', 'medium', '', false, true, 35, 'user@example.com', false, false, true, false);

-- ============================================================================
-- INSERT RELATIONSHIP DATA
-- ============================================================================

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('1', 'API Key 1', 'sk-example123');
INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('1', 'API Key 2', 'sk-backup456');
INSERT INTO subscription_promo_codes (subscription_id, promo_code) VALUES ('1', 'XYZ20');
INSERT INTO subscription_promo_codes (subscription_id, promo_code) VALUES ('1', 'LABOR25');
INSERT INTO subscription_account_emails (subscription_id, email) VALUES ('1', 'myemail1@domain.com');
INSERT INTO subscription_account_emails (subscription_id, email) VALUES ('1', 'testemail@domain.com');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('2', 'API Key 1', 'claude-api-key-123');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('12', 'API Key 1', 'pplx-api-key');
INSERT INTO subscription_promo_codes (subscription_id, promo_code) VALUES ('12', 'SEARCH20');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('22', 'API Key 1', 'leonardo-api-key');

INSERT INTO subscription_promo_codes (subscription_id, promo_code) VALUES ('25', 'PHOTO20');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('27', 'API Key 1', 'removebg-api-key');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('30', 'API Key 1', 'unsplash-api-key');

INSERT INTO subscription_promo_codes (subscription_id, promo_code) VALUES ('31', 'VIDEO20');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('35', 'API Key 1', 'eleven-api-key');
INSERT INTO subscription_promo_codes (subscription_id, promo_code) VALUES ('35', 'VOICE15');

INSERT INTO subscription_promo_codes (subscription_id, promo_code) VALUES ('38', 'CODE20');

INSERT INTO subscription_promo_codes (subscription_id, promo_code) VALUES ('46', 'WRITE20');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('48', 'API Key 1', 'hf-api-key');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('49', 'API Key 1', 'google-ai-key');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('50', 'API Key 1', 'deepai-api-key');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('51', 'API Key 1', 'claude-code-key');

INSERT INTO subscription_promo_codes (subscription_id, promo_code) VALUES ('54', 'TERMINAL20');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('55', 'API Key 1', 'zapier-api-key');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('57', 'API Key 1', 'pinecone-api-key');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('58', 'API Key 1', 'weaviate-api-key');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('59', 'API Key 1', 'amadeus-api-key');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('60', 'API Key 1', 'linear-api-key');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('62', 'API Key 1', 'figma-api-key');
INSERT INTO subscription_promo_codes (subscription_id, promo_code) VALUES ('62', 'DESIGN20');

INSERT INTO subscription_promo_codes (subscription_id, promo_code) VALUES ('67', 'SUPER20');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('68', 'API Key 1', 'notion-api-key');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('69', 'API Key 1', 'supabase-api-key');

INSERT INTO subscription_api_keys (subscription_id, key_name, key_value) VALUES ('70', 'API Key 1', 'vercel-api-key');

COMMIT;

-- ============================================================================
-- END OF DATA INSERTION
-- ============================================================================